name: Test 256
favicon: null
layout_spectrum: 0.019631024450063705
typography_spectrum: 0.6833360043819994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#334d5c'
    - '#ffffff'
    - '#e05b49'
    - '#adb1b4'
    - '#000000'
  brandStrength: 1
  lightness: 0.1603103526867926
  saturation: 0.6812185356393456
  rhythmicContrast: 0.6597377466969192
purpose: []
